# Generated by Django 5.1.4 on 2025-01-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentreport',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='harassmentreport',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
