# Generated by Django 5.1.4 on 2025-01-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_harassmentreport_latitude_harassmentreport_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentreport',
            name='reported_by',
            field=models.CharField(choices=[('victim', 'Victim'), ('eyewitness', 'Eyewitness')], default='victim', max_length=50),
        ),
        migrations.AlterField(
            model_name='harassmentreport',
            name='harassment_type',
            field=models.CharField(choices=[('verbal', 'Verbal'), ('physical', 'Physical'), ('cyber', 'Cyber'), ('sexual', 'Sexual'), ('emotional', 'Emotional or Psychological'), ('stalking', 'Stalking'), ('workplace', 'Workplace'), ('public', 'Public'), ('intimidation', 'Intimidation'), ('discrimination', 'Discrimination'), ('invasive', 'Invasive Questions'), ('gossip', 'Gossip and Rumors'), ('other', 'Other')], max_length=100),
        ),
    ]
