# Generated by Django 5.1.4 on 2025-01-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_harassmentreport_reported_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentreport',
            name='reported_by',
            field=models.CharField(choices=[('victim', 'Victim'), ('eyewitness', 'Eyewitness')], default='victim', max_length=50),
        ),
    ]
