# Generated by Django 5.1.4 on 2025-01-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_harassmentreport_reported_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='harassmentreport',
            name='reported_by',
            field=models.CharField(choices=[('victim', 'Victim'), ('non-victim', 'Non-Victim')], default='victim', max_length=50),
        ),
    ]
