# Generated by Django 5.1.4 on 2025-02-17 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_predictedhotspot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='harassmentreport',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.harassmentreport')),
            ],
            options={
                'unique_together': {('ip_address', 'report')},
            },
        ),
    ]
