# Generated by Django 5.1.4 on 2025-01-22 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_harassmentreport_reported_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harassmentreport',
            name='reported_by',
        ),
    ]
