# Generated by Django 5.1.4 on 2025-02-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_alter_harassmentreport_reported_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictedHotspot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('prediction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='harassmentreport',
            name='harassment_type',
            field=models.CharField(choices=[('arson', 'Arson'), ('assault', 'Assault'), ('burglary', 'Burglary'), ('counterfeiting', 'Counterfeiting'), ('cybercrime', 'Cybercrime'), ('domestic_violence', 'Domestic Violence'), ('drug_offense', 'Drug Offense'), ('extortion', 'Extortion'), ('firearm_offense', 'Firearm Offense'), ('fraud', 'Fraud'), ('homicide', 'Homicide'), ('identity_theft', 'Identity Theft'), ('illegal_possession', 'Illegal Possession'), ('kidnapping', 'Kidnapping'), ('public_intoxication', 'Public Intoxication'), ('robbery', 'Robbery'), ('sexual_assault', 'Sexual Assault'), ('shoplifting', 'Shoplifting'), ('traffic_violation', 'Traffic Violation'), ('vandalism', 'Vandalism'), ('vehicle_stolen', 'Vehicle - Stolen')], max_length=100),
        ),
    ]
